USE campuscloud;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'resources' AND COLUMN_NAME = 'is_approved')
    ALTER TABLE resources ADD is_approved BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'resources' AND COLUMN_NAME = 'status')
    ALTER TABLE resources ADD status NVARCHAR(50) NOT NULL DEFAULT 'pending';